import { Hero } from '@/components';
import ContactUs from '@/components/ContactUs';

export const metadata = {
  title: "Contact | Big Bin",
  description: "Generated by create next app",
};

export default function Contact() {
  return (
    <>
      <ContactUs />
    </>
  );
}
