import { Hero } from '@/components';

export const metadata = {
  title: "Contact | Big Bin",
  description: "Generated by create next app",
};

export default function Contact() {
  return (
    <>
      <Hero />
    </>
  );
}
