import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import { Footer, Navbar } from "@/components";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import { GoogleTagManager } from '@next/third-parties/google'


const roboto = Roboto({ subsets: ["latin"], weight: ['100', '300', '400', '500', '700', '900'] });

export const metadata = {
  title: "Home | Big Bin",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GoogleTagManager gtmId="GTM-MR2F9HCM" />
      <body className={`${roboto.className}`}>
        <Navbar />
        <ToastContainer position="top-right" />
        {children}
        <Footer />
      </body>
    </html>
  );
}
